package doggytalents.client.entity.model.animation.biganim;

import doggytalents.api.enu.forward_imitate.anim.AnimationDefinition;
import doggytalents.api.enu.forward_imitate.anim.Keyframe;
import doggytalents.api.enu.forward_imitate.anim.KeyframeAnimations;
import doggytalents.api.enu.forward_imitate.anim.AnimationChannel;

public class BellyRubAnimation {

    public static AnimationDefinition build() {
        var animDef = AnimationDefinition.Builder.withLength(11f);
        build1(animDef);
        build2(animDef);
        build3(animDef);
        return animDef.build();
    }

    private static void build1(AnimationDefinition.Builder builder) {
        builder.addAnimation("tail",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, -3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0.75f, -8f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2f, KeyframeAnimations.posVec(1.5f, -6.75f, -1.75f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(1.5f, -6.75f, -1.75f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8f, KeyframeAnimations.posVec(1.5f, -6.75f, -1.75f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.834334f, KeyframeAnimations.posVec(1.01f, -7.48f, -2.16f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.834334f, KeyframeAnimations.posVec(0f, -9f, -3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(11f, KeyframeAnimations.posVec(0f, -9f, -3f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(119.65f, 31.32f, 16.48f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(118.3f, -26.95f, -13.71f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(119.65f, 31.32f, 16.48f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.625f, KeyframeAnimations.degreeVec(118.3f, -26.95f, -13.71f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(119.65f, 31.32f, 16.48f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(118.3f, -26.95f, -13.71f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(119.65f, 31.32f, 16.48f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.375f, KeyframeAnimations.degreeVec(118.3f, -26.95f, -13.71f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(65.75f, 23.52f, 31.75f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.25f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.4583435f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.875f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.2916765f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.7083435f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.9167665f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.125f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.343333f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.583433f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.791677f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.041677f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.25f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.458343f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.676667f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.875f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.083433f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.291677f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.541677f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.791677f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7.041677f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7.625f, KeyframeAnimations.degreeVec(65.48f, -24.85f, 52.8f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7.875f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8f, KeyframeAnimations.degreeVec(58.71f, 43.53f, 19.24f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.834334f, KeyframeAnimations.degreeVec(122.56f, -46.93f, -25.73f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(9.083434f, KeyframeAnimations.degreeVec(111.91f, 9.97f, 3.27f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(9.343334f, KeyframeAnimations.degreeVec(122.56f, -46.93f, -25.73f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(9.583434f, KeyframeAnimations.degreeVec(111.91f, 9.97f, 3.27f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10f, KeyframeAnimations.degreeVec(122.56f, -46.93f, -25.73f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.5f, KeyframeAnimations.degreeVec(111.91f, 9.97f, 3.27f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.834334f, KeyframeAnimations.degreeVec(119.65f, 31.32f, 16.48f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(11f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.2916767f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.834334f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.708344f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(11f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.75f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(-25.58f, -8.93f, -17.97f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(-26.2f, -6.75f, -13.43f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.25f, KeyframeAnimations.degreeVec(-16.71f, -5.33f, -8.61f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(-26.2f, -6.75f, -13.43f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.0416765f, KeyframeAnimations.degreeVec(-16.71f, -5.33f, -8.61f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.4583435f, KeyframeAnimations.degreeVec(-26.2f, -6.75f, -13.43f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.8343335f, KeyframeAnimations.degreeVec(-16.71f, -5.33f, -8.61f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.25f, KeyframeAnimations.degreeVec(-26.2f, -6.75f, -13.43f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.676667f, KeyframeAnimations.degreeVec(-16.71f, -5.33f, -8.61f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.125f, KeyframeAnimations.degreeVec(-26.2f, -6.75f, -13.43f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.5f, KeyframeAnimations.degreeVec(-16.71f, -5.33f, -8.61f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.834333f, KeyframeAnimations.degreeVec(-26.2f, -6.75f, -13.43f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.25f, KeyframeAnimations.degreeVec(-16.71f, -5.33f, -8.61f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.625f, KeyframeAnimations.degreeVec(-26.2f, -6.75f, -13.43f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-16.71f, -5.33f, -8.61f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8f, KeyframeAnimations.degreeVec(-16.71f, -5.33f, -8.61f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.834334f, KeyframeAnimations.degreeVec(-20.05f, -3.6f, -5.81f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10f, KeyframeAnimations.degreeVec(-20.05f, -3.6f, -5.81f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.583434f, KeyframeAnimations.degreeVec(-20.76f, -16.88f, -37.35f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.708344f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(11f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1f, KeyframeAnimations.posVec(-1f, -1f, 0.5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.2916767f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.8343333f, KeyframeAnimations.posVec(-0.6f, 0.9f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(-0.61f, -0.85f, 1.01f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.5f, KeyframeAnimations.posVec(-0.61f, -0.85f, 1.01f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.834334f, KeyframeAnimations.posVec(-0.6f, -1.1f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10f, KeyframeAnimations.posVec(-0.6f, -1.1f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.834334f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(11f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)));
    }

    private static void build2(AnimationDefinition.Builder builder) {
        builder.addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(-26.89f, -3.8f, -3.25f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(-16.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(-31.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.4167665f, KeyframeAnimations.degreeVec(-16.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.8343335f, KeyframeAnimations.degreeVec(-31.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.25f, KeyframeAnimations.degreeVec(-16.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.6766665f, KeyframeAnimations.degreeVec(-31.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.083433f, KeyframeAnimations.degreeVec(-16.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.458343f, KeyframeAnimations.degreeVec(-31.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.75f, KeyframeAnimations.degreeVec(-16.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5f, KeyframeAnimations.degreeVec(-31.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.208343f, KeyframeAnimations.degreeVec(-16.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.625f, KeyframeAnimations.degreeVec(-31.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.041677f, KeyframeAnimations.degreeVec(-16.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.416767f, KeyframeAnimations.degreeVec(-31.29f, 21.83f, 51.84f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-31.53f, 20.8f, 50.33f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.5f, KeyframeAnimations.degreeVec(-31.53f, 20.8f, 50.33f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.834334f, KeyframeAnimations.degreeVec(-29.56f, -24.22f, -15.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10f, KeyframeAnimations.degreeVec(-29.56f, -24.22f, -15.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.583434f, KeyframeAnimations.degreeVec(-23.33f, 14.48f, 32.52f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.834334f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(11f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.2916767f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, -6f, -3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, -6f, -3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.5f, KeyframeAnimations.posVec(0f, -6f, -3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.834334f, KeyframeAnimations.posVec(0f, -4.25f, -3.27f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.834334f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(11f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(-85f, -20f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(-77.65f, -11.97f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.375f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.7083435f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.4583435f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.7916765f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.167667f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.75f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.416767f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.75f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.125f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.458343f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.5f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.834334f, KeyframeAnimations.degreeVec(-35.91f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10f, KeyframeAnimations.degreeVec(-35.91f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.583434f, KeyframeAnimations.degreeVec(-69.45f, 38.16f, 13.04f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.834334f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(11f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.2916767f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, -2.75f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, -2.75f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.5f, KeyframeAnimations.posVec(0f, -2.75f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.834334f, KeyframeAnimations.posVec(-1f, -3.5f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.834334f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(11f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(-90.71f, 34.12f, -6.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(-76.95f, 26.47f, 23.63f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(-7.63f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(-12.63f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.25f, KeyframeAnimations.degreeVec(-5.13f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.5f, KeyframeAnimations.degreeVec(-12.63f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.75f, KeyframeAnimations.degreeVec(-5.13f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-12.63f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.25f, KeyframeAnimations.degreeVec(-5.13f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(-12.63f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.75f, KeyframeAnimations.degreeVec(-5.13f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4f, KeyframeAnimations.degreeVec(-12.63f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.25f, KeyframeAnimations.degreeVec(-5.13f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(-12.63f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.75f, KeyframeAnimations.degreeVec(-5.13f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5f, KeyframeAnimations.degreeVec(-12.63f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.208343f, KeyframeAnimations.degreeVec(-5.13f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.458343f, KeyframeAnimations.degreeVec(-12.63f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.708343f, KeyframeAnimations.degreeVec(-5.13f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.958343f, KeyframeAnimations.degreeVec(-12.63f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.208343f, KeyframeAnimations.degreeVec(-5.13f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.458343f, KeyframeAnimations.degreeVec(-12.63f, 12.95f, 59.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-12.86f, 12.52f, 57.68f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.5f, KeyframeAnimations.degreeVec(-12.86f, 12.52f, 57.68f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.834334f, KeyframeAnimations.degreeVec(-33.81f, -9.18f, -10.16f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10f, KeyframeAnimations.degreeVec(-16.88f, -6.38f, -5.98f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.583434f, KeyframeAnimations.degreeVec(-58.05f, 45.79f, 23.07f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.834334f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(11f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)));
    }

    private static void build3(AnimationDefinition.Builder builder) {
        builder.addAnimation("upper_body",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -1.69f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -1.69f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.2916767f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2f, KeyframeAnimations.posVec(0.25f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.3433335f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.7083435f, KeyframeAnimations.posVec(0.25f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.0416765f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.4167665f, KeyframeAnimations.posVec(0.25f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.75f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.375f, KeyframeAnimations.posVec(0.25f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.916767f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(5.791677f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.375f, KeyframeAnimations.posVec(0.25f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.5f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.834334f, KeyframeAnimations.posVec(-1f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.834334f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(11f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("upper_body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(-22.09f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.75f, KeyframeAnimations.degreeVec(-22.09f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(-8f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(-14.9f, 10.21f, 33.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(-19.9f, 10.21f, 33.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.4167665f, KeyframeAnimations.degreeVec(-14.9f, 10.21f, 33.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.7083435f, KeyframeAnimations.degreeVec(-19.9f, 10.21f, 33.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.125f, KeyframeAnimations.degreeVec(-14.9f, 10.21f, 33.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(-19.9f, 10.21f, 33.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.75f, KeyframeAnimations.degreeVec(-14.9f, 10.21f, 33.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.208343f, KeyframeAnimations.degreeVec(-19.9f, 10.21f, 33.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.834333f, KeyframeAnimations.degreeVec(-14.9f, 10.21f, 33.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.375f, KeyframeAnimations.degreeVec(-19.9f, 10.21f, 33.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.916767f, KeyframeAnimations.degreeVec(-14.9f, 10.21f, 33.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.375f, KeyframeAnimations.degreeVec(-19.9f, 10.21f, 33.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-14.88f, 9.69f, 31.97f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.5f, KeyframeAnimations.degreeVec(-14.88f, 9.69f, 31.97f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.834334f, KeyframeAnimations.degreeVec(-18.34f, -4.86f, -19.13f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.834334f, KeyframeAnimations.degreeVec(-28f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(11f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -3.76f, -2.02f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -3.76f, -2.02f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.2916767f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.8343333f, KeyframeAnimations.posVec(0.25f, -3.5f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2f, KeyframeAnimations.posVec(0.25f, -3.25f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.2083435f, KeyframeAnimations.posVec(0.25f, -3.5f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.625f, KeyframeAnimations.posVec(0.25f, -3.25f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.0416765f, KeyframeAnimations.posVec(0.25f, -3.5f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.4583435f, KeyframeAnimations.posVec(0.25f, -3.25f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.8343335f, KeyframeAnimations.posVec(0.25f, -3.5f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.25f, KeyframeAnimations.posVec(0.25f, -3.25f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.676667f, KeyframeAnimations.posVec(0.25f, -3.5f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(5.083433f, KeyframeAnimations.posVec(0.25f, -3.25f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(5.416767f, KeyframeAnimations.posVec(0.25f, -3.25f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(5.791677f, KeyframeAnimations.posVec(0.25f, -3.5f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.208343f, KeyframeAnimations.posVec(0.25f, -3.25f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.625f, KeyframeAnimations.posVec(0.25f, -3.5f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0.25f, -3.25f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.5f, KeyframeAnimations.posVec(0.25f, -3.25f, -1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.834334f, KeyframeAnimations.posVec(-1.03f, -2.6f, -0.88f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.834334f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(11f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(-47.84f, -0.27f, -0.41f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.75f, KeyframeAnimations.degreeVec(-47.84f, -0.27f, -0.41f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(-22.45f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(-29.95f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.4583435f, KeyframeAnimations.degreeVec(-22.45f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.9167665f, KeyframeAnimations.degreeVec(-29.95f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.2083435f, KeyframeAnimations.degreeVec(-22.45f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.6766665f, KeyframeAnimations.degreeVec(-29.95f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.125f, KeyframeAnimations.degreeVec(-22.45f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.583433f, KeyframeAnimations.degreeVec(-29.95f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5f, KeyframeAnimations.degreeVec(-22.45f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.167667f, KeyframeAnimations.degreeVec(-22.45f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.625f, KeyframeAnimations.degreeVec(-29.95f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.083433f, KeyframeAnimations.degreeVec(-22.45f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.541677f, KeyframeAnimations.degreeVec(-29.95f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-22.45f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.5f, KeyframeAnimations.degreeVec(-22.45f, 17.85f, 27.15f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.834334f, KeyframeAnimations.degreeVec(-27.13f, 12.12f, 16.58f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.834334f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(11f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0.25f, 0.25f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0.25f, 0.25f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1f, KeyframeAnimations.posVec(0f, -1.17f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.1676667f, KeyframeAnimations.posVec(0f, 0.37f, -0.02f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, -1.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.25f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.5f, KeyframeAnimations.posVec(0f, -1.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.75f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -1.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.25f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -1.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.75f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4f, KeyframeAnimations.posVec(0f, -1.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.25f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.5f, KeyframeAnimations.posVec(0f, -1.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.75f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(5f, KeyframeAnimations.posVec(0f, -1.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(5.208343f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(5.458343f, KeyframeAnimations.posVec(0f, -1.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(5.708343f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(5.958343f, KeyframeAnimations.posVec(0f, -1.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.208343f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.458343f, KeyframeAnimations.posVec(0f, -1.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.708343f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(-0.01f, -1.23f, 0.01f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.5f, KeyframeAnimations.posVec(-0.01f, -1.23f, 0.01f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.834334f, KeyframeAnimations.posVec(-2.25f, 0.25f, 0.5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(11f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-22.5f, 0f, 26.88f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(-33.15f, 15.89f, 51.96f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.625f, KeyframeAnimations.degreeVec(-22.5f, 0f, 26.88f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.75f, KeyframeAnimations.degreeVec(-36.36f, 0f, 29.21f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(-22.5f, 0f, 26.88f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(40.23f, 11.15f, -10.59f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.25f, KeyframeAnimations.degreeVec(40.75f, -8.59f, 12.12f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(3.18f, -8.17f, -20.74f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.6766665f, KeyframeAnimations.degreeVec(4.42f, -20.08f, -70.67f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.208343f, KeyframeAnimations.degreeVec(-45.58f, -13.55f, -8.02f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-38.93f, -28.89f, -25.79f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.5f, KeyframeAnimations.degreeVec(-38.93f, -28.89f, -25.79f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.834334f, KeyframeAnimations.degreeVec(-9.41f, -46.4f, -72.2f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(9.167666f, KeyframeAnimations.degreeVec(-9.41f, -46.4f, -72.2f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(9.343334f, KeyframeAnimations.degreeVec(-25.02f, 30.5f, -82.88f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(9.625f, KeyframeAnimations.degreeVec(-25.02f, 30.5f, -82.88f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(9.916766f, KeyframeAnimations.degreeVec(-58.99f, -27.66f, -58.42f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.583434f, KeyframeAnimations.degreeVec(-30.36f, -16.59f, -21f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.834334f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(11f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("root",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.1676667f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0.5f, -6f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.8343333f, KeyframeAnimations.posVec(2f, -7.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.208343f, KeyframeAnimations.posVec(2f, -8f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(5.583433f, KeyframeAnimations.posVec(2f, -7.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(2f, -8f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.343334f, KeyframeAnimations.posVec(2f, -8f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(8.834334f, KeyframeAnimations.posVec(1.36f, -6.43f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.291676f, KeyframeAnimations.posVec(1.36f, -5.43f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.583434f, KeyframeAnimations.posVec(0.4f, 3.64f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.834334f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(11f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("root",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(22.42f, 1.91f, 125.38f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.208343f, KeyframeAnimations.degreeVec(22.48f, -0.96f, 132.31f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.583433f, KeyframeAnimations.degreeVec(22.42f, 1.91f, 125.38f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(22.48f, -0.96f, 132.31f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.343334f, KeyframeAnimations.degreeVec(22.48f, -0.96f, 132.31f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.834334f, KeyframeAnimations.degreeVec(15.27f, -0.65f, 89.86f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.291676f, KeyframeAnimations.degreeVec(15.27f, -0.65f, 89.86f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.583434f, KeyframeAnimations.degreeVec(-21.4f, 9.64f, -10.4f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.834334f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(11f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(9f, KeyframeAnimations.posVec(0f, -0.05f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.343334f, KeyframeAnimations.posVec(0f, -0.52f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(11f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, -12.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.375f, KeyframeAnimations.degreeVec(5.67f, 20.4f, -38.45f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(32.5f, 37.5f, -12.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.75f, KeyframeAnimations.degreeVec(-45f, 0f, -12.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(25f, 0f, -12.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.25f, KeyframeAnimations.degreeVec(9.41f, -10.59f, -46.83f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(17.68f, 2.15f, -2.73f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(-10.29f, 7.13f, 21.86f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(25.92f, -4.75f, -34.52f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.7083435f, KeyframeAnimations.degreeVec(24.69f, 9.45f, -63.85f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.2916765f, KeyframeAnimations.degreeVec(-24.54f, -6.92f, -29.99f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(36.23f, -15.94f, -8.93f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.791677f, KeyframeAnimations.degreeVec(14.41f, -13.16f, -21.52f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.343333f, KeyframeAnimations.degreeVec(36.23f, -15.94f, -8.93f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.625f, KeyframeAnimations.degreeVec(14.41f, -13.16f, -21.52f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.167667f, KeyframeAnimations.degreeVec(36.23f, -15.94f, -8.93f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.458343f, KeyframeAnimations.degreeVec(14.41f, -13.16f, -21.52f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(36.23f, -15.94f, -8.93f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7.291677f, KeyframeAnimations.degreeVec(14.41f, -13.16f, -21.52f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8f, KeyframeAnimations.degreeVec(14.41f, -13.16f, -21.52f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.25f, KeyframeAnimations.degreeVec(18.42f, 39.94f, -6.11f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(9f, KeyframeAnimations.degreeVec(56.06f, 73.51f, 11.44f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(9.916766f, KeyframeAnimations.degreeVec(56.06f, 73.51f, 11.44f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.125f, KeyframeAnimations.degreeVec(36.23f, 15.94f, 8.93f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.343334f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.834334f, KeyframeAnimations.degreeVec(40.32f, -0.37f, -0.21f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(11f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(9f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(10.343334f, KeyframeAnimations.posVec(0f, -0.52f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(11f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 12.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.375f, KeyframeAnimations.degreeVec(5.67f, -20.4f, 38.45f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(32.5f, -37.5f, 12.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.75f, KeyframeAnimations.degreeVec(-45f, 0f, 12.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(15f, 0f, 12.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.25f, KeyframeAnimations.degreeVec(-6.37f, 12.63f, -22.25f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(17.68f, -2.15f, 2.73f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(-10.29f, -7.13f, -21.86f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(25.92f, 4.75f, 34.52f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.7083435f, KeyframeAnimations.degreeVec(24.69f, -9.45f, 63.85f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.2916765f, KeyframeAnimations.degreeVec(-24.54f, 6.92f, 29.99f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(36.23f, 15.94f, 8.93f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.791677f, KeyframeAnimations.degreeVec(14.41f, 13.16f, 21.52f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(5.343333f, KeyframeAnimations.degreeVec(36.23f, 15.94f, 8.93f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.167667f, KeyframeAnimations.degreeVec(36.23f, 15.94f, 8.93f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.458343f, KeyframeAnimations.degreeVec(14.41f, 13.16f, 21.52f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(36.23f, 15.94f, 8.93f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7.291677f, KeyframeAnimations.degreeVec(14.41f, 13.16f, 21.52f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(8.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(9f, KeyframeAnimations.degreeVec(-8.12f, 4.76f, -0.92f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(9.291676f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(9.5f, KeyframeAnimations.degreeVec(0f, -72.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.343334f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(10.834334f, KeyframeAnimations.degreeVec(42.54f, 1.7f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(11f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)));
    } 
    
}
