package doggytalents.client.entity.model.animation.biganim;

import doggytalents.api.enu.forward_imitate.anim.AnimationDefinition;
import doggytalents.api.enu.forward_imitate.anim.Keyframe;
import doggytalents.api.enu.forward_imitate.anim.KeyframeAnimations;
import doggytalents.api.enu.forward_imitate.anim.AnimationChannel;

public class StrechAnimation {
    
    public static AnimationDefinition build() {
        var animDef = AnimationDefinition.Builder.withLength(3.5f).looping();
        build1(animDef);
        build2(animDef);
        build3(animDef);
        return animDef.build();
    }

    public static void build1(AnimationDefinition.Builder builder) {
        builder.addAnimation("right_ear",
        new AnimationChannel(AnimationChannel.Targets.POSITION, 
            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM), 
            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                AnimationChannel.Interpolations.CATMULLROM), 
            new Keyframe(1f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                AnimationChannel.Interpolations.CATMULLROM), 
            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, -0.32f, 0f),
                AnimationChannel.Interpolations.CATMULLROM), 
            new Keyframe(2.9167665f, KeyframeAnimations.posVec(0f, -0.41f, 0f),
                AnimationChannel.Interpolations.CATMULLROM), 
            new Keyframe(3.3433335f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_ear",
        new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(-44.28f, 14.61f, -13.81f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(0f, 47.5f, -22.5f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.625f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.2083435f, KeyframeAnimations.degreeVec(0f, 47.5f, -22.5f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.9167665f, KeyframeAnimations.degreeVec(-42.5f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3.3433335f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_ear",
        new AnimationChannel(AnimationChannel.Targets.POSITION, 
            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM), 
            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                AnimationChannel.Interpolations.CATMULLROM), 
            new Keyframe(1f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                AnimationChannel.Interpolations.CATMULLROM), 
            new Keyframe(2.9167665f, KeyframeAnimations.posVec(0f, -0.54f, 0f),
                AnimationChannel.Interpolations.CATMULLROM), 
            new Keyframe(3.3433335f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_ear",
        new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(-44.28f, -14.61f, 13.81f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(0f, -47.5f, 22.5f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.9583433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-11.26f, -35.16f, 20.52f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.9167665f, KeyframeAnimations.degreeVec(-42.5f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3.3433335f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
      .addAnimation("head",
          new AnimationChannel(AnimationChannel.Targets.POSITION,
              new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -5f, 1f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(2.5f, KeyframeAnimations.posVec(0f, -5f, 1f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                  AnimationChannel.Interpolations.CATMULLROM)))
      .addAnimation("head",
          new AnimationChannel(AnimationChannel.Targets.ROTATION,
              new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(0.375f, KeyframeAnimations.degreeVec(-6.16f, -4.29f, -34.77f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, -22.5f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(1f, KeyframeAnimations.degreeVec(7.16f, 2.25f, -17.36f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(1.25f, KeyframeAnimations.degreeVec(-14.34f, -4.46f, -16.94f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(1.625f, KeyframeAnimations.degreeVec(0f, 0f, -35f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(2f, KeyframeAnimations.degreeVec(-7.16f, -2.25f, -17.36f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(0f, 0f, -35f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(2.625f, KeyframeAnimations.degreeVec(-22.91f, -10.29f, -22.91f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                  AnimationChannel.Interpolations.CATMULLROM)))
      .addAnimation("body",
          new AnimationChannel(AnimationChannel.Targets.POSITION,
              new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -3f, 0f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(2.5f, KeyframeAnimations.posVec(0f, -3f, 0f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                  AnimationChannel.Interpolations.CATMULLROM)))
      .addAnimation("body",
          new AnimationChannel(AnimationChannel.Targets.ROTATION,
              new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(0.5f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(0.75f, KeyframeAnimations.degreeVec(19.93f, -1.71f, 4.7f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(1f, KeyframeAnimations.degreeVec(19.93f, 1.71f, -4.7f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(1.25f, KeyframeAnimations.degreeVec(19.93f, -1.71f, 4.7f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(1.5f, KeyframeAnimations.degreeVec(19.93f, 1.71f, -4.7f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(1.75f, KeyframeAnimations.degreeVec(19.93f, -1.71f, 4.7f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(2f, KeyframeAnimations.degreeVec(19.93f, 1.71f, -4.7f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(2.25f, KeyframeAnimations.degreeVec(19.93f, -1.71f, 4.7f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(2.5f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                  AnimationChannel.Interpolations.CATMULLROM),
              new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                  AnimationChannel.Interpolations.CATMULLROM)));
    }
    public static void build2(AnimationDefinition.Builder builder) {
        builder.addAnimation("right_hind_leg",
        new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5f, KeyframeAnimations.degreeVec(8f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.5f, KeyframeAnimations.degreeVec(8f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_hind_leg",
        new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5f, KeyframeAnimations.degreeVec(8f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.5f, KeyframeAnimations.degreeVec(8f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_front_leg",
        new AnimationChannel(AnimationChannel.Targets.POSITION,
            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -3.5f, 2f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.0834333f, KeyframeAnimations.posVec(0f, -3.5f, 2f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.4167667f, KeyframeAnimations.posVec(0f, -4.5f, 2f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, -3.5f, 2f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, -3.5f, 2f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("right_front_leg",
        new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(-77.5f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_front_leg",
        new AnimationChannel(AnimationChannel.Targets.POSITION,
            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -3.5f, 2f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.0834333f, KeyframeAnimations.posVec(0f, -3.5f, 2f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.4167667f, KeyframeAnimations.posVec(0f, -4.5f, 2f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, -3.5f, 2f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, -3.5f, 2f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("left_front_leg",
        new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(-65f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("tail",
        new AnimationChannel(AnimationChannel.Targets.POSITION,
            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -1.5f, -1.25f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, -1.5f, -1.25f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("tail",
        new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5f, KeyframeAnimations.degreeVec(165f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.75f, KeyframeAnimations.degreeVec(166.94f, 7.44f, 29.15f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1f, KeyframeAnimations.degreeVec(166.94f, -7.44f, -29.15f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.25f, KeyframeAnimations.degreeVec(166.94f, 7.44f, 29.15f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.5f, KeyframeAnimations.degreeVec(166.94f, -7.44f, -29.15f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.75f, KeyframeAnimations.degreeVec(166.94f, 7.44f, 29.15f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2f, KeyframeAnimations.degreeVec(166.94f, -7.44f, -29.15f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.25f, KeyframeAnimations.degreeVec(166.94f, 7.44f, 29.15f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.5f, KeyframeAnimations.degreeVec(165f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("upper_body",
        new AnimationChannel(AnimationChannel.Targets.POSITION,
            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -4f, 2f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.5f, KeyframeAnimations.posVec(0f, -4f, 2f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)))
    .addAnimation("upper_body",
        new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(19.93f, -1.71f, 4.7f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(19.93f, 1.71f, -4.7f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(19.93f, -1.71f, 4.7f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.4167667f, KeyframeAnimations.degreeVec(19.93f, 1.71f, -4.7f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(19.93f, -1.71f, 4.7f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.9167667f, KeyframeAnimations.degreeVec(19.93f, 1.71f, -4.7f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(19.93f, -1.71f, 4.7f),
                AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.CATMULLROM)));
    }
    public static void build3(AnimationDefinition.Builder builder) {}

}
