modLoader="javafml"
loaderVersion="${fml_version_range}"
license="GNU GPLv3"
issueTrackerURL="https://github.com/DashieDev/DoggyTalentsNext/issues"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/doggy-talents-next"
logoFile="dt_background.png"
[[mods]] #mandatory
    modId="doggytalents"
    version="${file.jarVersion}"
    updateJSONURL="https://raw.githubusercontent.com/DashieDev/DoggyTalentsNext/master/check_for_update/update.json"
    displayName="Doggy Talents Next"
    credits="dashiedev, mashxp"
    authors="dashiedev, mashxp"
    description="The next generation of the beloved-by-many DoggyTalents. Turning your wolves into fun, playful, skillful dogs."
[[dependencies.doggytalents]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.doggytalents]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
