modLoader="javafml"
loaderVersion="${neofml_version_range}"
license="GNU LGPLv3"
issueTrackerURL="https://github.com/DashieDev/DoggyTalentsNext/issues"
displayURL="https://minecraft.curseforge.com/projects/doggy-talents-next/"
logoFile="dt_background.png"
[[mods]] #mandatory
    modId="doggytalents"
    version="${file.jarVersion}"
    updateJSONURL="https://raw.githubusercontent.com/DashieDev/DoggyTalentsNext/0d05eaff7c4b588831ca6480f737187f44dda820/check_for_update/update.json"
    displayName="Doggy Talents Next"
    credits="silverstarshiro, stefanbech and the DTN Discord Server."
    authors="dashiedev, mashxp"
    description="Minecraft Wolf, reimagined."
[[dependencies.doggytalents]] #optional
    modId="neoforge"
    mandatory=true
    versionRange="${neoforge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.doggytalents]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
