package doggytalents.client.entity.model.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class DogAnimationSequences2 {
    
    
        public static final AnimationDefinition SIT_TO_REST = AnimationDefinition.Builder.withLength(2f)
            .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -5.5f, 1.75f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.25f, KeyframeAnimations.posVec(0f, -4.75f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.75f, KeyframeAnimations.posVec(0f, -5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(2.54f, 0.43f, 9.99f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.75f, KeyframeAnimations.degreeVec(-7.54f, 0.76f, 2.5f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -4f, -2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -6.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -6f, -5f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(-0.5f, -7f, 1f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-90f, 22.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -6f, -5f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0.5f, -7f, 1f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-90f, -22.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_front_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -6.75f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_front_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-87.41f, 14.99f, 0.67f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(-87.41f, 14.99f, 0.67f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_front_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -6.75f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_front_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-87.41f, -14.99f, -0.67f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(-87.41f, -14.99f, -0.67f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tail",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, -2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -7f, -0.25f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tail",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("upper_body",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -2f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -6.5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, -6.5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("upper_body",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_ear",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_ear",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.75f, KeyframeAnimations.degreeVec(26.57f, 14.48f, -26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(14.07f, 14.48f, -26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.25f, KeyframeAnimations.degreeVec(26.57f, 14.48f, -26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.625f, KeyframeAnimations.degreeVec(14.07f, 14.48f, -26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(50.57f, 67.38f, 17.13f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(26.57f, 14.48f, -26.57f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_ear",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_ear",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.75f, KeyframeAnimations.degreeVec(26.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(16.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.25f, KeyframeAnimations.degreeVec(26.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.625f, KeyframeAnimations.degreeVec(16.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(26.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM))).build();
        public static final AnimationDefinition REST_IDLE = AnimationDefinition.Builder.withLength(1f).looping()
            .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -4.5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-7.54f, 0.76f, 2.5f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(-5.04f, 0.76f, 2.5f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(-7.54f, 0.76f, 2.5f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -6.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -5.75f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -6.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-4.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(0.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(-0.5f, -7f, 1f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(-0.5f, -7f, 1f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 22.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.625f, KeyframeAnimations.degreeVec(-87.52f, 22.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(-90f, 22.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0.5f, -7f, 1f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0.5f, -7f, 1f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, -22.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-90f, -25f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(-90f, -22.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_front_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -6.75f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_front_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-87.41f, 14.99f, 0.67f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-85.93f, 13.99f, 0.6f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(-87.41f, 14.99f, 0.67f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_front_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -6.75f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_front_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-87.41f, -14.99f, -0.67f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.375f, KeyframeAnimations.degreeVec(-85.91f, -14.99f, -0.67f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(-87.41f, -14.99f, -0.67f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tail",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -6.5f, -0.25f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -7f, -0.25f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -6.5f, -0.25f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tail",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("upper_body",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -6.5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -6.25f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -6.5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("upper_body",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.625f, KeyframeAnimations.degreeVec(0.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_ear",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_ear",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(26.57f, 14.48f, -26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(14.79f, 14.33f, -13.66f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(26.57f, 14.48f, -26.57f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_ear",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_ear",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(26.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(17.46f, -15.95f, 13.7f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(26.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM))).build();
        public static final AnimationDefinition REST_TO_SIT = AnimationDefinition.Builder.withLength(3.25f)
            .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.625f, KeyframeAnimations.posVec(0f, -5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.375f, KeyframeAnimations.posVec(0f, -5f, 1.75f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.875f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2.25f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(3.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-7.54f, 0.76f, 2.5f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.375f, KeyframeAnimations.degreeVec(2.54f, 0.43f, 9.99f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.25f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(3.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -6.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.375f, KeyframeAnimations.posVec(0f, -6.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.875f, KeyframeAnimations.posVec(0f, -4f, -2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2.3433335f, KeyframeAnimations.posVec(0f, -4f, -2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2.9583435f, KeyframeAnimations.posVec(0f, -3.58f, -2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(3.25f, KeyframeAnimations.posVec(0f, -4f, -2f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0.125f, KeyframeAnimations.degreeVec(0.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.375f, KeyframeAnimations.degreeVec(0.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.875f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(3.25f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0.125f, KeyframeAnimations.posVec(-0.5f, -7f, 1f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.375f, KeyframeAnimations.posVec(-0.5f, -7f, 1f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.875f, KeyframeAnimations.posVec(0f, -6f, -5f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(3.25f, KeyframeAnimations.posVec(0f, -6f, -5f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0.125f, KeyframeAnimations.degreeVec(-90f, 22.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.375f, KeyframeAnimations.degreeVec(-90f, 22.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.875f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.25f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(3.25f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0.125f, KeyframeAnimations.posVec(0.5f, -7f, 1f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.375f, KeyframeAnimations.posVec(0.5f, -7f, 1f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.875f, KeyframeAnimations.posVec(0f, -6f, -5f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(3.25f, KeyframeAnimations.posVec(0f, -6f, -5f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0.125f, KeyframeAnimations.degreeVec(-90f, -22.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.375f, KeyframeAnimations.degreeVec(-90f, -22.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.875f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(3.25f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_front_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(1.375f, KeyframeAnimations.posVec(0f, -6.75f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.875f, KeyframeAnimations.posVec(0f, -1f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(3.25f, KeyframeAnimations.posVec(0f, -1f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_front_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-87.41f, 14.99f, 0.67f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-87.41f, 14.99f, 0.67f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.375f, KeyframeAnimations.degreeVec(-87.41f, 14.99f, 0.67f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.875f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(3.25f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_front_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(1.375f, KeyframeAnimations.posVec(0f, -6.75f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.875f, KeyframeAnimations.posVec(0f, -1f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(3.25f, KeyframeAnimations.posVec(0f, -1f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_front_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-87.41f, -14.99f, -0.67f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-87.41f, -14.99f, -0.67f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.375f, KeyframeAnimations.degreeVec(-87.41f, -14.99f, -0.67f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.875f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(3.25f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tail",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -6.5f, -0.25f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.375f, KeyframeAnimations.posVec(0f, -7f, -0.25f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.875f, KeyframeAnimations.posVec(0f, -9f, -2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2.25f, KeyframeAnimations.posVec(0f, -9f, -2.5f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2.5f, KeyframeAnimations.posVec(0f, -9f, -2.78f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2.75f, KeyframeAnimations.posVec(0f, -9f, -2.78f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(3f, KeyframeAnimations.posVec(0f, -9f, -3.04f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(3.25f, KeyframeAnimations.posVec(0f, -9f, -2f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tail",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.25f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.75f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(3.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("upper_body",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -6.5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -6.5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.375f, KeyframeAnimations.posVec(0f, -6.5f, 2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.875f, KeyframeAnimations.posVec(0f, -2f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2.25f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2.75f, KeyframeAnimations.posVec(0f, -2.25f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(3.25f, KeyframeAnimations.posVec(0f, -2f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("upper_body",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0.125f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.375f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.875f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(3.25f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_ear",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.4583433f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.875f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(3.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_ear",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(26.57f, 14.48f, -26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(50.57f, 67.38f, 17.13f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.625f, KeyframeAnimations.degreeVec(26.57f, 14.48f, -26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(14.07f, 14.48f, -26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.125f, KeyframeAnimations.degreeVec(26.57f, 14.48f, -26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.2916765f, KeyframeAnimations.degreeVec(7.48f, -2.24f, 0.85f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(1.28f, -9.8f, -7.65f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(3.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_ear",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.4583433f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1.875f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(3.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_ear",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(26.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0f, KeyframeAnimations.degreeVec(26.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.25f, KeyframeAnimations.degreeVec(16.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.625f, KeyframeAnimations.degreeVec(26.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(16.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.125f, KeyframeAnimations.degreeVec(26.57f, -14.48f, 26.57f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(2.91f, -11.47f, 7.36f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.5416765f, KeyframeAnimations.degreeVec(-8.86f, -3.71f, 7.82f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(3.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM))).build();

        public static final AnimationDefinition FLY_JUMP_START = AnimationDefinition.Builder.withLength(0.5f)
            .addAnimation("tail",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -2f, -2f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -1.18f, -1.63f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tail",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(140.68f, -23.93f, -26.34f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(84.84f, -5.13f, -5.65f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_front_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -3f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -1.21f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_front_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-60f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-84.33f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_front_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -3f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -1.21f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_front_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-60f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-100.98f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -1.85f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.375f, KeyframeAnimations.degreeVec(87.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(78.49f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -1.85f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(59.61f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("upper_body",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -3f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -1.21f, 0.46f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("upper_body",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-9.67f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -3f, -1f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-13.12f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("root",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 2.03f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_ear",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -0.6f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_ear",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-51.16f, 34.39f, -35.05f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(55f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-55.69f, 2.98f, -3.43f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_ear",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -0.6f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_ear",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-51.16f, -34.39f, 35.05f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(55f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-55.69f, -2.98f, 3.43f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, -3f, -1f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -1.03f, -1.32f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(1.02f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("elytra",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -0.24f, 1.45f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("elytra",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(24.59f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_wing",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -60f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-15.18f, -46.68f, 11.36f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_wing",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 60f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-15.18f, 46.68f, -11.36f),
                        AnimationChannel.Interpolations.CATMULLROM))).build();
        public static final AnimationDefinition FLY_AIR_BOURNE = AnimationDefinition.Builder.withLength(2f).looping()
            .addAnimation("tail",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -1.18f, -1.63f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -1.32f, -1.72f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, -1.18f, -1.63f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tail",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(84.84f, -5.13f, -5.65f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(107.34f, -5.13f, -5.65f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(84.84f, -5.13f, -5.65f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_front_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -1.21f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -1.47f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, -1.21f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_front_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-84.33f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(-95.72f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(-84.33f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_front_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -1.21f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -1.47f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, -1.21f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_front_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-100.98f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(-82.18f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(-100.98f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1.85f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1.65f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, -1.85f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(78.49f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(69.05f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(78.49f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1.85f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1.65f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, -1.85f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(59.61f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(74.61f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(59.61f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("upper_body",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -1.21f, 0.46f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -1.47f, 0.41f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, -1.21f, 0.46f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("upper_body",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-9.67f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(-15.18f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(-9.67f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-13.12f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(-13.12f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("root",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 2.03f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, 1.78f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, 2.03f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_ear",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.6f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -0.6f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, -0.6f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_ear",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-55.69f, 2.98f, -3.43f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-40.69f, 2.98f, -3.43f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(-55.69f, 2.98f, -3.43f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.5f, KeyframeAnimations.degreeVec(-40.69f, 2.98f, -3.43f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(-55.69f, 2.98f, -3.43f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_ear",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.6f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -0.6f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, -0.6f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_ear",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-55.69f, -2.98f, 3.43f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(-40.69f, -2.98f, 3.43f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(-55.69f, -2.98f, 3.43f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1.5f, KeyframeAnimations.degreeVec(-40.69f, -2.98f, 3.43f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(-55.69f, -2.98f, 3.43f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -1.03f, -1.32f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -2.19f, -1.3f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, -1.03f, -1.32f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(1.02f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(7.34f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(1.02f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("elytra",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.24f, 1.45f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(1f, KeyframeAnimations.posVec(0f, -0.23f, 1.38f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(2f, KeyframeAnimations.posVec(0f, -0.24f, 1.45f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("elytra",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(24.59f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(17.64f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(24.59f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_wing",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-15.18f, -46.68f, 11.36f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -51.48f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(-15.18f, -46.68f, 11.36f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_wing",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-15.18f, 46.68f, -11.36f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 51.48f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(2f, KeyframeAnimations.degreeVec(-15.18f, 46.68f, -11.36f),
                        AnimationChannel.Interpolations.CATMULLROM))).build();
        public static final AnimationDefinition FLY_LANDING = AnimationDefinition.Builder.withLength(0.5f)
            .addAnimation("tail",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -1.18f, -1.63f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tail",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(84.84f, -5.13f, -5.65f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.25f, KeyframeAnimations.degreeVec(140f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.375f, KeyframeAnimations.degreeVec(29.22f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_front_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -1.21f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_front_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-84.33f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-74.5f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_front_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -1.21f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_front_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-100.98f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1.85f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(78.49f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1.85f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_hind_leg",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(59.61f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("upper_body",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -1.21f, 0.46f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("upper_body",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-9.67f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, -0.75f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-13.12f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("root",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, 2.03f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 3f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_ear",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.35f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, -0.35f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_ear",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-55.69f, 2.98f, -3.43f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(58f, 19.35f, -11.7f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_ear",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.35f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, -0.35f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_ear",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-55.69f, -2.98f, 3.43f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(58f, -19.35f, 11.7f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -1.03f, -1.32f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(1.02f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("elytra",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                    new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.24f, 1.45f),
                        AnimationChannel.Interpolations.CATMULLROM), 
                    new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("elytra",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(24.59f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("right_wing",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-15.18f, -46.68f, 11.36f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("left_wing",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                    new Keyframe(0f, KeyframeAnimations.degreeVec(-15.18f, 46.68f, -11.36f),
                        AnimationChannel.Interpolations.CATMULLROM),
                    new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                        AnimationChannel.Interpolations.CATMULLROM))).build();

}
