package doggytalents.client.entity.model.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class DogAnimationSequences3 {
    public static final AnimationDefinition NAKEY = AnimationDefinition.Builder.withLength(7f)
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0.5f, 3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.5f, KeyframeAnimations.posVec(0f, 0.5f, 3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, 2.25f, 2.25f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.3f, KeyframeAnimations.posVec(0f, 2.25f, 2.25f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.5f, KeyframeAnimations.posVec(0f, 2.28f, 2.04f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.2f, KeyframeAnimations.posVec(0f, 2.28f, 2.04f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.5f, KeyframeAnimations.posVec(0f, 1.92f, 1.74f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.4f, KeyframeAnimations.posVec(0f, 1.92f, 1.74f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.9f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(54.06f, -9.73f, 2.34f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.8f, KeyframeAnimations.degreeVec(54.06f, -9.73f, 2.34f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(43.13f, 27.07f, 23.09f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.3f, KeyframeAnimations.degreeVec(43.13f, 27.07f, 23.09f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8f, KeyframeAnimations.degreeVec(43.13f, 27.07f, 23.09f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(42.3f, -25.23f, -21.2f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.8f, KeyframeAnimations.degreeVec(42.3f, -25.23f, -21.2f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.3f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(-9.19f, 2.39f, 2.01f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.2f, KeyframeAnimations.degreeVec(-9.19f, 2.39f, 2.01f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(-7.31f, 1.77f, 1.49f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.4f, KeyframeAnimations.degreeVec(-7.31f, 1.77f, 1.49f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.9f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -1.75f, -1.25f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -2.32f, -1.44f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.3f, KeyframeAnimations.posVec(0f, -2.32f, -1.44f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -2.43f, -1.48f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.2f, KeyframeAnimations.posVec(0f, -2.43f, -1.48f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.5f, KeyframeAnimations.posVec(0f, -2.73f, -1.58f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.4f, KeyframeAnimations.posVec(0f, -2.73f, -1.58f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.9f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(-72.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.7f, KeyframeAnimations.degreeVec(-72.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(-72.7f, 11.95f, 3.69f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(-69.63f, -5.75f, -2.66f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-65.68f, -2.36f, -1.02f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.3f, KeyframeAnimations.degreeVec(-65.68f, -2.36f, -1.02f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(-64.18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.2f, KeyframeAnimations.degreeVec(-64.18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(-60.47f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.4f, KeyframeAnimations.degreeVec(-60.47f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.9f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.1f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.3f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.2f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.5f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.4f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.9f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(-90f, 25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.1f, KeyframeAnimations.degreeVec(-90f, 49.86f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-90f, 25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.3f, KeyframeAnimations.degreeVec(-90f, 25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(-90f, -5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.2f, KeyframeAnimations.degreeVec(-90f, -5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(-90f, -6.08f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.4f, KeyframeAnimations.degreeVec(-90f, -6.08f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.9f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.3f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.2f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.5f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.4f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.9f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(-90f, -25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.4f, KeyframeAnimations.degreeVec(-90f, -52.28f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-90f, -25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.3f, KeyframeAnimations.degreeVec(-90f, -25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.2f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(-90f, 1.31f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.4f, KeyframeAnimations.degreeVec(-90f, 1.31f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.9f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5f, KeyframeAnimations.posVec(-1f, 4f, 3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.1f, KeyframeAnimations.posVec(-0.07f, 4.41f, 3.21f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(-1f, 4f, 3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.3f, KeyframeAnimations.posVec(-1f, 4f, 3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.5f, KeyframeAnimations.posVec(-1f, 1f, 3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.2f, KeyframeAnimations.posVec(-1f, 1f, 3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.5f, KeyframeAnimations.posVec(-0.9f, 0.64f, 2.7f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.4f, KeyframeAnimations.posVec(-0.9f, 0.64f, 2.7f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.9f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(-20.59f, 17.86f, 39.23f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.8f, KeyframeAnimations.degreeVec(-20.59f, 17.86f, 39.23f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.1f, KeyframeAnimations.degreeVec(-8.4f, 26.6f, 72.22f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(-22.22f, 16.97f, 36.85f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-20.59f, 17.86f, 39.23f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.3f, KeyframeAnimations.degreeVec(-20.59f, 17.86f, 39.23f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(-25.58f, -8.93f, -17.97f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.2f, KeyframeAnimations.degreeVec(-25.58f, -8.93f, -17.97f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(-25.99f, -9.45f, -19.19f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.4f, KeyframeAnimations.degreeVec(-25.99f, -9.45f, -19.19f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.9f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5f, KeyframeAnimations.posVec(1f, 2f, 3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(1f, 2f, 3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.3f, KeyframeAnimations.posVec(1f, 2f, 3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.5f, KeyframeAnimations.posVec(0.94f, 1.82f, 2.82f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.2f, KeyframeAnimations.posVec(0.94f, 1.82f, 2.82f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.5f, KeyframeAnimations.posVec(0.8f, 1.39f, 2.39f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.4f, KeyframeAnimations.posVec(0.8f, 1.39f, 2.39f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.9f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(-17.23f, -21.11f, -49.27f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8f, KeyframeAnimations.degreeVec(-17.23f, -21.11f, -49.27f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(-9.02f, -27.25f, -72.06f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-17.23f, -21.11f, -49.27f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.3f, KeyframeAnimations.degreeVec(-17.23f, -21.11f, -49.27f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(-26.65f, 4.52f, 8.93f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.2f, KeyframeAnimations.degreeVec(-26.65f, 4.52f, 8.93f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(-27.18f, 5.42f, 11.1f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.4f, KeyframeAnimations.degreeVec(-27.18f, 5.42f, 11.1f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.9f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -9f, -4f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -9f, -3.49f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.3f, KeyframeAnimations.posVec(0f, -9f, -3.49f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -9f, -3.39f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.2f, KeyframeAnimations.posVec(0f, -9f, -3.39f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.5f, KeyframeAnimations.posVec(0f, -9f, -3.12f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.4f, KeyframeAnimations.posVec(0f, -9f, -3.12f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.9f, KeyframeAnimations.posVec(0f, -9f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, -9f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 35f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.1f, KeyframeAnimations.degreeVec(0f, -38.67f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 35f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, -38.67f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.9f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("upper_body",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0.75f, 2.5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1f, KeyframeAnimations.posVec(0f, 0.6f, 3.3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, 0.25f, 1.75f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.3f, KeyframeAnimations.posVec(0f, 0.25f, 1.75f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.5f, KeyframeAnimations.posVec(0f, 0.07f, 1.57f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.2f, KeyframeAnimations.posVec(0f, 0.07f, 1.57f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.5f, KeyframeAnimations.posVec(0f, -0.24f, 1.34f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.4f, KeyframeAnimations.posVec(0f, -0.24f, 1.34f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.9f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("upper_body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(-13f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.7f, KeyframeAnimations.degreeVec(-13f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(-12.11f, 3.2f, 12.09f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.7f, KeyframeAnimations.degreeVec(0.39f, 3.2f, 12.09f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(7.69f, -4.32f, -20.03f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-28f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.3f, KeyframeAnimations.degreeVec(-28f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(-28.82f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.2f, KeyframeAnimations.degreeVec(-28.82f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(-27.02f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.4f, KeyframeAnimations.degreeVec(-27.02f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.9f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.9f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.7f, KeyframeAnimations.degreeVec(8.26f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8f, KeyframeAnimations.degreeVec(8.26f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.1f, KeyframeAnimations.degreeVec(3.66f, -47.44f, -2.7f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-42.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.1f, KeyframeAnimations.degreeVec(9.17f, 3.51f, 0.2f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, 40f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.2f, KeyframeAnimations.degreeVec(0f, 0f, 40f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(0f, 0f, 40f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.6f, KeyframeAnimations.degreeVec(0f, 0f, -25f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.9f, KeyframeAnimations.degreeVec(0f, 0f, 34.17f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(6.9f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(-47.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.7f, KeyframeAnimations.degreeVec(20.72f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.2f, KeyframeAnimations.degreeVec(26.7f, 34.43f, 15.87f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-42.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.1f, KeyframeAnimations.degreeVec(-13.55f, -11.04f, -13.65f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, -27.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.2f, KeyframeAnimations.degreeVec(0f, 0f, -27.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(0f, 0f, -27.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.6f, KeyframeAnimations.degreeVec(0f, 0f, -37.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(6.9f, KeyframeAnimations.degreeVec(0f, 0f, 17.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("root",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.3f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3.5f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.2f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(4.5f, KeyframeAnimations.posVec(-4f, -6.75f, 0f),
                    AnimationChannel.Interpolations.LINEAR), 
                new Keyframe(6.4f, KeyframeAnimations.posVec(-4f, -6.75f, 0f),
                    AnimationChannel.Interpolations.LINEAR), 
                new Keyframe(7f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("root",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.5f, KeyframeAnimations.degreeVec(0f, 0f, -90f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.6f, KeyframeAnimations.degreeVec(0f, 0f, -97.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(4.7f, KeyframeAnimations.degreeVec(0f, 0f, -89.61f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, -89.61f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition DRUNK_START = AnimationDefinition.Builder.withLength(1.8f)
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.3f, KeyframeAnimations.posVec(0f, -5.5f, 1.75f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.9f, KeyframeAnimations.posVec(0f, -5f, 2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.6f, KeyframeAnimations.posVec(-0.01f, -1.9f, 0.36f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.3f, KeyframeAnimations.degreeVec(2.54f, 0.43f, 9.99f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9f, KeyframeAnimations.degreeVec(-7.54f, 0.76f, 2.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(-38.87f, -25.09f, -23.41f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.3f, KeyframeAnimations.posVec(0f, -6.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.9f, KeyframeAnimations.posVec(0f, -6.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.6f, KeyframeAnimations.posVec(0.21f, -3.81f, -0.83f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.3f, KeyframeAnimations.degreeVec(0.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9f, KeyframeAnimations.degreeVec(0.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(-18.36f, 14.74f, 22.42f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.3f, KeyframeAnimations.posVec(-0.5f, -7f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.9f, KeyframeAnimations.posVec(-0.5f, -7f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.6f, KeyframeAnimations.posVec(-0.09f, -3.49f, -0.65f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.3f, KeyframeAnimations.degreeVec(-90f, 22.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9f, KeyframeAnimations.degreeVec(-90f, 22.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(-26.7f, 14.23f, 47.53f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.3f, KeyframeAnimations.posVec(0.5f, -7f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.9f, KeyframeAnimations.posVec(0.5f, -7f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.6f, KeyframeAnimations.posVec(0.09f, -6.17f, -2.3f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.3f, KeyframeAnimations.degreeVec(-90f, -22.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9f, KeyframeAnimations.degreeVec(-90f, -22.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(-38.05f, -3.87f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.3f, KeyframeAnimations.posVec(0f, -6.75f, 2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.9f, KeyframeAnimations.posVec(0f, -6.75f, 2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.6f, KeyframeAnimations.posVec(-0.5f, -2f, 1.18f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.3f, KeyframeAnimations.degreeVec(-87.41f, 14.99f, 0.67f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9f, KeyframeAnimations.degreeVec(-87.41f, 14.99f, 0.67f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(-42.32f, 19.74f, 41.58f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.3f, KeyframeAnimations.posVec(0f, -6.75f, 2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.9f, KeyframeAnimations.posVec(0f, -6.75f, 2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.6f, KeyframeAnimations.posVec(0f, -2f, 0.35f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.3f, KeyframeAnimations.degreeVec(-87.41f, -14.99f, -0.67f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9f, KeyframeAnimations.degreeVec(-87.41f, -14.99f, -0.67f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(-29.77f, 2.06f, -2.6f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.3f, KeyframeAnimations.posVec(0f, -7f, -0.25f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.9f, KeyframeAnimations.posVec(0f, -6.5f, -0.25f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.6f, KeyframeAnimations.posVec(1.24f, -6.7f, -1.49f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.3f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(0f, 29.9f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("upper_body",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.3f, KeyframeAnimations.posVec(0f, -6.5f, 2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.9f, KeyframeAnimations.posVec(0f, -6.5f, 2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.6f, KeyframeAnimations.posVec(0f, -2.79f, 0.35f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("upper_body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.3f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(-12.78f, 7.97f, 26.29f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.2f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.9f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.6f, KeyframeAnimations.posVec(0f, -0.12f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.2f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(26.57f, 14.48f, -26.57f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.8f, KeyframeAnimations.degreeVec(14.07f, 14.48f, -26.57f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9f, KeyframeAnimations.degreeVec(26.57f, 14.48f, -26.57f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(37.09f, 13.5f, -46.64f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.2f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.9f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.6f, KeyframeAnimations.posVec(0f, -0.51f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.2f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(26.57f, -14.48f, 26.57f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.8f, KeyframeAnimations.degreeVec(16.57f, -14.48f, 26.57f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9f, KeyframeAnimations.degreeVec(26.57f, -14.48f, 26.57f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(32.5f, 13.82f, -32.62f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("root",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0.9f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR), 
                new Keyframe(1.6f, KeyframeAnimations.posVec(2f, -8f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("root",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0.9f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(22.48f, -0.96f, 132.31f),
                    AnimationChannel.Interpolations.CATMULLROM))).build();
}
