package doggytalents.client.entity.model.animation;

import doggytalents.api.enu.forward_imitate.anim.AnimationChannel;
import doggytalents.api.enu.forward_imitate.anim.AnimationDefinition;
import doggytalents.api.enu.forward_imitate.anim.Keyframe;
import doggytalents.api.enu.forward_imitate.anim.KeyframeAnimations;

public class DogBackHugAnimationSequences {
    
    public static final AnimationDefinition BACKHUG_START = AnimationDefinition.Builder.withLength(1.5f)
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, -1.5f, -0.25f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.25f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 2.75f, 2f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.75f, KeyframeAnimations.degreeVec(-22.55f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -3.58f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.0834333f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.3433333f, KeyframeAnimations.posVec(0f, -3.58f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -2.58f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-70f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.25f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-90f, 27.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-92.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-92.14f, -36.12f, 1.3f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.25f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-90f, -27.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.25f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 1f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-15.29f, 12.54f, 24.68f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.25f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-12f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.25f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 1f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(-16.16f, -10.35f, -20.09f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.25f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-12f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, -3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1f, KeyframeAnimations.posVec(0f, -9f, -3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -9f, -4f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("upper_body",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -2.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.25f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("upper_body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-9.4f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.25f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-33f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.625f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, -0.42f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.375f, KeyframeAnimations.posVec(0f, -0.73f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -0.24f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(1.41f, -1.01f, 32.48f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(1.64f, 0.57f, -22.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.375f, KeyframeAnimations.degreeVec(0.98f, -1.43f, 52.48f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-24.78f, 1.4f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.9167666f, KeyframeAnimations.posVec(0f, -0.41f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.375f, KeyframeAnimations.posVec(0f, -0.73f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -0.23f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(1.39f, 1.04f, -39.97f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(5.46f, 33.83f, -46.37f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.375f, KeyframeAnimations.degreeVec(0.98f, -1.43f, 52.48f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-24.78f, 1.4f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("root",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 3f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 3f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, -204.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, -180f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition BACKHUG_END = AnimationDefinition.Builder.withLength(3f)
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 2.75f, 2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, -1.5f, -0.25f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.25f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.5f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.29167674f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.75f, KeyframeAnimations.degreeVec(-22.55f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.25f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, -50f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.25f, KeyframeAnimations.degreeVec(-0.27f, 1.22f, 49.37f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.5416765f, KeyframeAnimations.degreeVec(-0.84f, -0.23f, -54.53f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -2.58f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.16766674f, KeyframeAnimations.posVec(0f, -3.58f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.41676674f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -3.58f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.1676667f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.6766667f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2f, KeyframeAnimations.posVec(0f, -3.58f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.4167665f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -4f, -2f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-70f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.16766674f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 27.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.25f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.5f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -6f, -5f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, -27.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-92.14f, -36.12f, 1.3f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.4167665f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-12f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.7916766f, KeyframeAnimations.degreeVec(-15.29f, 12.54f, 24.68f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-12f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-16.16f, -10.35f, -20.09f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-27f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -9f, -4f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -9f, -3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -9f, -3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.75f, KeyframeAnimations.posVec(0f, -9f, -3f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -9f, -3f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.75f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.25f, KeyframeAnimations.degreeVec(0f, 40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, -40f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("upper_body",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 1f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.25f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.75f, KeyframeAnimations.posVec(0f, -2.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.125f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2f, KeyframeAnimations.posVec(0f, -2.25f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.375f, KeyframeAnimations.posVec(0f, -2.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("upper_body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-33f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.25f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-9.4f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.0416765f, KeyframeAnimations.degreeVec(-15.93f, -5.71f, -19.2f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.2916765f, KeyframeAnimations.degreeVec(-15.29f, 7.61f, 25.58f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(-14.82f, -9.11f, -30.47f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.24f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -0.73f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, -0.42f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.875f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, -0.43f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.9583433f, KeyframeAnimations.posVec(0f, -0.89f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.5416765f, KeyframeAnimations.posVec(0f, -0.46f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-24.78f, 1.4f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.125f, KeyframeAnimations.degreeVec(0.98f, -1.43f, 52.48f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.41676674f, KeyframeAnimations.degreeVec(1.64f, 0.57f, -22.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(1.41f, -1.01f, 32.48f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(1.48f, -0.64f, 19.99f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(1.05f, -1.08f, 41.14f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.125f, KeyframeAnimations.degreeVec(0.97f, 0.24f, -33.7f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.4167665f, KeyframeAnimations.degreeVec(0.27f, -0.31f, 55.35f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(0.21f, -0.04f, -19.26f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION, 
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.23f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -0.73f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, -0.41f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(1.7916767f, KeyframeAnimations.posVec(0f, -0.42f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.25f, KeyframeAnimations.posVec(0f, -0.98f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(2.5834335f, KeyframeAnimations.posVec(0f, -0.56f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM), 
                new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-24.78f, 1.4f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.125f, KeyframeAnimations.degreeVec(0.98f, -1.43f, 52.48f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.41676674f, KeyframeAnimations.degreeVec(5.46f, 33.83f, -46.37f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(1.39f, 1.04f, -39.97f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.625f, KeyframeAnimations.degreeVec(1.5f, 0.6f, -24.99f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(1.29f, -0.77f, 29.19f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.0834335f, KeyframeAnimations.degreeVec(0.71f, 0.76f, -59.18f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.375f, KeyframeAnimations.degreeVec(0.45f, 0.01f, 27.06f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(0.15f, 0.11f, -33.61f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("root",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -180f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.34333326f, KeyframeAnimations.degreeVec(0f, -204.5f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, 3f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.625f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM))).build();
}
